name = "mm-lyrics-plus-cors-proxy-1"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-12-19"

routes = [{ pattern = "cors-proxy.spicetify.app", custom_domain = true }]

[observability.logs]
enabled = false
